# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rubocop', '~> 1.57'

group :development, :test do
  gem 'rubocop-minitest' # or gem 'rubocop-rspec' depending on your test suite
  gem 'rubocop-performance'
  gem 'rubocop-rails'
end
